package game.core.db.dto;

public class OrderRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_a.uid
	 * @mbggenerated
	 */
	private Long uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_a.roleId
	 * @mbggenerated
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_a.name
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_a.uid
	 * @return  the value of t_a.uid
	 * @mbggenerated
	 */
	public Long getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_a.uid
	 * @param uid  the value for t_a.uid
	 * @mbggenerated
	 */
	public void setUid(Long uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_a.roleId
	 * @return  the value of t_a.roleId
	 * @mbggenerated
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_a.roleId
	 * @param roleId  the value for t_a.roleId
	 * @mbggenerated
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_a.name
	 * @return  the value of t_a.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_a.name
	 * @param name  the value for t_a.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}